"""empty message

Revision ID: a124070fd2d6
Revises: fcdab7de564e
Create Date: 2025-08-22 22:55:25.006792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a124070fd2d6'
down_revision = 'fcdab7de564e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint('empresa_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint('empresa_nombre_key', ['nombre'])

    # ### end Alembic commands ###
